all:main

client: client.py
	@echo "executing client script..."
	@python3 client.py

server: server.py
	@echo "executing server script..."
	@python3 server.py

main: main.py
	@echo "executing main script..."
	@python3 main.py